
project_id = "rojydqsndhoielitdquu"

[auth.email]
# Email auth provider is enabled by default.
enabled = true

[api]
# Port to use for the API URL.
port = 8080

[db]
# Port to use for the local database URL.
port = 5432

[db.shadow]
# Port to use for the local shadow database URL.
port = 5433

[studio]
# Port to use for Supabase Studio.
port = 8082

[storage]
# The maximum file size in bytes that can be uploaded to storage.
file_size_limit = "50MiB"

[functions]
[functions.create-google-meet-link]
# Required JWT verification for the edge function
verify_jwt = true
