name = "skillshare-sync-connect"
compatibility_date = "2024-01-01"

[env.production]
name = "skillshare-sync-connect"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages configuration
[[pages_builds]]
build_command = "npm run build"
build_output_directory = "dist"
