
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rojydqsndhoielitdquu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvanlkcXNuZGhvaWVsaXRkcXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTM2MTgsImV4cCI6MjA2MDMyOTYxOH0.CPvCmtErCNAQ0mAbXBUAzShvI9eytI8Hi6tm_Z-66SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'supabase.auth.token',
    }
  }
);
